---
language: python
python: "2.7.12"
sudo: required
group: deprecated-2017Q4

services:
  - docker
install:
  - pip install ansible==2.4.1.0
  - pip install molecule==1.25.0
  - pip install ansible-lint==3.4.20
  - pip install docker
script:
  - molecule test --driver docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
